### ISSUE TITLE
How it use? How to build?

### ISSUE THREAD

**Issue by nihirash** [Virtuos86/guick#1]
Absolutely absent description about building or running your sources. 

Please add information.

**Comment by Virtuos86** [comment]
А что по-вражески? Проект мерт безоговорочно.

Это не нативное приложение. Поэтому пользоваться неудобно :). Запускается через эту штуку: https://play.google.com/store/apps/details?id=com.smartphoneremote.androidscriptfree. Устанавливаешь DroidScript и дальше два пути:

1.) Скачиваешь репу, упаковываешь в zip (можно сразу zip'ом скачать) и переименовываешь расширение на ".spk". Потом выбирай этот файл в любом файловом менеджере на андроиде и следуй инструкциям по установке. Дальше идешь в DroidScript и запускаешь.
2.) Скачал репу, закидывай на карту памяти в каталог "DrodScript/Guick". Дальше идешь в DroidScript и запускаешь.

Вообще, можно и apk собрать, но плагин для этого стоит 1тыр, поэтому мне не надо :).

Я, кстати, не обещаю, что запустится вообще, с тех пор уже и Угнич поменялся, и сайт.

**Comment by nihirash** [comment]
По английски, чисто из уважения к международному сегменту. 

Прямо говоря - стало просто любопытно на чем это дело было сделано.

**Comment by Virtuos86** [comment]
Инструмент, если серьезно, неплохой. Пилит один человек, ну и еще небольшая команда добавляет свое местами, в основном плагины. Хотя есть и недочеты. [Этот клиент](https://github.com/Virtuos86/play-rust-lang) показывает немного, что можно делать вполне обычные и нормально выглядящие приложения.
